### ISSUE TITLE
Can't find where libmcrypt4 and libmcrypt-dev are installed?

### ISSUE THREAD

**Issue by thinkv** [ddollar/heroku-buildpack-apt#23]
trying to get this to work but these libs aren't recognised by my app on heroku.

-----> Installing libmcrypt4_2.5.8-3.1ubuntu1_amd64.deb
-----> Installing libmcrypt-dev_2.5.8-3.1ubuntu1_amd64.deb

Seems to install fine, but I can't find them anywhere, any ideas?

**Comment by lvh** [comment]
Seems like they're in `.apt/` in the home directory of the heroku user.
