### ISSUE TITLE
failed to compile Multipack app

### ISSUE THREAD

**Issue by Ndshah82** [ddollar/heroku-buildpack-apt#34]
I'm getting compilation errors when trying to install this buildpack.  Can you please help diagnose?  I'm using ruby 2.2.2 on an ubuntu 14.04 system.

Here are my environment logs:
2015-09-08T15:26:06.092697+00:00 heroku[slug-compiler]: Slug compilation started
2015-09-08T15:26:06.092705+00:00 heroku[slug-compiler]: Slug compilation failed: failed to compile Multipack app

Here is the output from from the installation:
remote: =====> Downloading Buildpack: https://github.com/ddollar/heroku-buildpack-apt
remote:
remote:  !     Push rejected, failed to compile Multipack app
remote:
remote: Verifying deploy...
remote:
remote: !	Push rejected to avant-ocr-staging-crm.

Please let me know if you need anything else from me.  It worked for me the first few time I installed and then suddenly stopped working.

**Comment by moustacheful** [comment]
I got the same error when there was no `Aptfile` are you sure you got that file in the repo?

**Comment by Ndshah82** [comment]
Yes I tried it both with and without that file.

**Comment by Ndshah82** [comment]
To be clear the file was in the root directory of my project

**Comment by thanpolas** [comment]
Hello, i'm not sure if this is related but the symptoms are the same, I keep getting "Push rejected, failed to compile Multipack app" errors when I first added this repo to my .buildpacks file... It was a working repository until i added this repo...

my `Aptfile` contains a single line "libavahi-compat-libdnssd-dev"

I have done anything i can think of including forking both this repo and the multipack one and pointing heroku to those, in these repos i added debug echo's in hopes to understand what's going on, my findings are that heroku bails when multipack tries to execute the `bin/detect` script of this repo...

I have added an `echo` [right before anything happens at this repo's detect](https://github.com/thanpolas/heroku-buildpack-apt/blob/master/bin/detect), I never see this echo...


As you can see [in Heroku's output](https://gist.github.com/thanpolas/dcdf7bc66aed71b0a875) the last thing that prints before quitting is:

> remote: INVOIKING detect from:/tmp/buildpackpCBBP with arg:/tmp/build_87cec8bbb0d2acb43e54bbdd8a574842

Which is the last `echo` I've put in the [cloned buildpack repo](https://github.com/thanpolas/heroku-buildpack-multi/blob/master/bin/compile#L59) before buildpack-multi execute this line:

```
framework=$($dir/bin/detect $1)
```

Help please
