### ISSUE TITLE
NPM can't find package installed by buildpack-apt

### ISSUE THREAD

**Issue by moustacheful** [ddollar/heroku-buildpack-apt#35]
I'm trying to install the package `libphash0-dev` and while it seems to install fine, I get the following error when the NPM package that depends on that library attempts to install I get:

```bash
remote:        Package pHash was not found in the pkg-config search path.
remote:        Perhaps you should add the directory containing `pHash.pc'
remote:        to the PKG_CONFIG_PATH environment variable
remote:        No package 'pHash' found
```
After setting the `PKG_CONFIG_PATH` as suggested to where I found the package installed by the buildpack `/app/.apt/usr/lib/pkgconfig/` the results are the same.

So the thing is I can't get it to install during build... But if I do it after the build process via 
```bash
$ heroku run bash
Running `bash` attached to terminal... up, run.6308
~ $ npm install phash-image
```
it installs correctly. 
I'm unsure whether this is a bug or I'm missing something. The packages just don't seem to be available at build time.

**Comment by crearc** [comment]
I'm running into a similar problem with installing `uuid-dev` for my python setup. It installs fine, but can't find it when it moves to the python buildpack. Find any solutions?
