### ISSUE TITLE
Adding sourcelist directive to apt options

### ISSUE THREAD

**Issue by russormes** [ddollar/heroku-buildpack-apt#37]
Thanks for the buildpack, it is very useful. 

I forked your repo and added Dir::Etc::sourcelist=$BUILD_DIR/repolist to the options list. This allows me to add a file repolist in my repo directory in order to download from no standard sources. 

Is this something that might be added to the buildpack or is this already handled in the Aptfile?

**Comment by Paveltarno** [comment]
+1!
