### ISSUE TITLE
Heroku Buildpacks detect fails

### ISSUE THREAD

**Issue by webjay** [ddollar/heroku-buildpack-apt#40]
-----> Fetching set buildpack https://github.com/ddollar/heroku-buildpack-apt... done
     !     Push rejected, failed to detect set buildpack https://github.com/ddollar/heroku-buildpack-apt
    More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure

This works:
https://github.com/webjay/heroku-buildpack-apt

**Comment by ddollar** [comment]
This should be fixed now.

**Comment by rickmed** [comment]
@ddollar  I'm getting the same thing

EDIT: nevermind had a typo AptFile

**Comment by mach-kernel** [comment]
I'm getting this same issue when using it on top of the regular Ruby buildpack :crying_cat_face: 

EDIT: also nevermind it turns out that I too have issues spelling things.
